version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: cotaku_db
    ports:
      - "8296:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cotaku

